---

# Default compose file for development and production.
# Should be used directly in development.
# Automatically loads `docker-compose.override.yml` if it exists.
# No extra steps required.
# Should be used together with `docker/docker-compose.prod.yml`
# in production.

version: "3.6"
services:
  nginx:
    image: nginx:1.13.12
    restart: always
    ports:
    - "9999:8000"
    networks:
    - webnet
    depends_on:
      - web
    volumes:
    - ./media/:/var/www/media
    - django-static:/var/www/static
    - django-media:/var/www/django/media/
    - ./docker/nginx/:/etc/nginx/conf.d
  web:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        DJANGO_ENV: development
    volumes:
      - .:/code
      - django-static:/code/static/
      - django-media:/var/www/django/media/
    depends_on:
      - db
      - redis
    networks:
      - webnet
    ports:
      - "5555:5555"
    env_file: ./config/.env
    environment:
      DJANGO_DATABASE_HOST: db
      DJANGO_SETTINGS_MODULE: 'server.settings'
    command: bash /code/docker/django/gunicorn.sh

  db:
    image: "postgres:9.6.9-alpine"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet
    env_file: ./config/.env

  redis:
    image: "redis:alpine"
    networks:
      - webnet
    env_file: ./config/.env

networks:
  webnet:

volumes:
  pgdata:
  django-static:
  django-media:
